---
apiVersion: metering.openshift.io/v1alpha1
kind: ReportQuery
metadata:
  labels:
    middleware-container-meter: "true"
  name: kube-pod-labels-com-redhat-product-raw
spec:
  columns:
    - name: pod
      type: varchar
      unit: kubernetes_pod
    - name: namespace
      type: varchar
      unit: kubernetes_namespace
    - name: product
      type: varchar
    - name: timestamp
      type: timestamp
      unit: date
    - name: dt
      type: varchar
  inputs:
    - default: kube-pod-labels-com-redhat-product
      name: KubePodLabelsComRedHatProductDataSourceName
      type: ReportDataSource
  query: |
    SELECT labels['pod'] as pod,
        labels['namespace'] as namespace,
        labels['label_com_redhat_product'] as product,
        "timestamp",
        dt
    FROM {| dataSourceTableName .Report.Inputs.KubePodLabelsComRedHatProductDataSourceName |}
    WHERE element_at(labels, 'pod') IS NOT NULL
